image: gitpod/workspace-full

tasks:
  - name: Docker Compose Backend
    init: |
      echo "Building backend container..."
    command: |
      docker-compose -f gitpod-docker-compose.yml up

  - name: Webhook Service
    init: |
      cd webhook-service
      npm install express crypto
    command: |
      cd webhook-service
      node webhook-service.js

ports:
  - port: 3001
    onOpen: open-browser
    visibility: public
  - port: 3002
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - ms-azuretools.vscode-docker
