version: '3.8'

services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./packages/backend:/app
      - backend-node-modules:/app/node_modules
    environment:
      - PORT=3001
      - NODE_ENV=production
    command: npx nodemon --legacy-watch src/index.js
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/app
      - frontend-node-modules:/app/node_modules
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://15.206.100.79:3001/api
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend

  webhook:
    build:
      context: ./webhook-service
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-your-webhook-secret}
      - REPO_PATH=/workspace
      - GIT_BRANCH=${GIT_BRANCH:-main}
      - TOUCH_PATHS=packages/backend/src/index.js,packages/frontend/src/index.js
      - NODEMON_RESTART_CMD=docker exec syncpoc_backend_1 touch /app/src/index.js
      - DEBUG=${DEBUG:-false}
    volumes:
      - .:/workspace
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - backend

volumes:
  backend-node-modules:
  frontend-node-modules:

networks:
  app-network:
    driver: bridge
