version: '3.8'

services:
  backend:
    build:
      context: ./packages/backend
    ports:
      - "3001:3001"
    volumes:
      - ./packages/backend:/app
      - backend-node-modules:/app/node_modules
    environment:
      - PORT=3001
      - NODE_ENV=development
      - GITPOD_WORKSPACE_URL=${GITPOD_WORKSPACE_URL}
    command: npx nodemon --legacy-watch src/index.js

volumes:
  backend-node-modules: