services:
  webhook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - WEBHOOK_SECRET=${WEBHOOK_SECRET:-your-webhook-secret}
      - REPO_PATH=/workspace
      - GIT_BRANCH=${GIT_BRANCH:-main}
      # Comma-separated list of files to touch when changes are detected
      - TOUCH_PATHS=packages/backend/src/index.js,packages/frontend/src/index.js
      # Optional custom command to restart nodemon
      - NODEMON_RESTART_CMD=docker exec syncpoc-backend-1 touch /app/src/index.js
      - DEBUG=${DEBUG:-false}
    volumes:
      # Mount the repository root to /workspace
      - .:/workspace
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    external: true
